# Generated by Django 3.2.9 on 2021-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickbay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
