# Generated by Django 3.2.9 on 2021-12-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickbay', '0002_auto_20211203_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='imagename',
        ),
    ]
