# Generated by Django 3.2.9 on 2021-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickbay', '0005_auto_20211205_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
