# Generated by Django 3.2.9 on 2021-12-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickbay', '0007_auto_20211206_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='image_caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imagename',
            new_name='image_name',
        ),
    ]
