# Generated by Django 3.2.9 on 2021-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickbay', '0008_auto_20211206_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
