# Generated by Django 3.2.9 on 2021-12-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickbay', '0012_alter_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
